---
- name: check_file
  hosts: localhost
  rules:
    - name: simple_rule
      sources:
        - ansible.eda.range:
            start: 1
            end: 1
            step: 1
      rules:
        - name: Print Hello
          condition: event.range.value == 1
          action:
            run_playbook:
              name: hello_playbook
              organization: Default
