---
- name: minimal-rulebook
  hosts: localhost
  sources: []

  rules:
    - name: simple-playbook
      condition: True
      action:
        run_playbook:
          name: hello_trigger
          organization: Default
