---
- name: minimal-rulebook
  hosts: localhost

  sources:
    - ansible.eda.tick:
        delay: 10   # событие каждые 10 секунд

  rules:
    - name: periodic-debug
      condition: True
      action:
        debug:
          msg: "Событие tick сработало! Event: {{ event }}"
