---
- name: minimal-rulebook
  hosts: localhost
  sources: []

  rules:
    - name: simple-playbook
      condition: True
      action:
        run_playbook:
          name: hello_trigger          # playbook, который будет запускаться
          organization: Default        # твоя организация
          inventory: Default           # inventory, который доступен в UI
