---
- name: Demo Rulebook
  hosts: localhost
  sources:
    - name: kafka_source
      ansible.eda.kafka:
        bootstrap_servers: "kafka:9092"
        topics:
          - demo_topic
        group_id: "demo_group"
        auto_offset_reset: "earliest"
  rules:
    - name: File created check
      condition: event.fileexists == true
      actions:
        - debug:
            msg: "File /tmp/demo_file.txt detected — Rule fired!"
