---
- name: minimal-rulebook
  hosts: localhost
  sources: []

  rules:
    - name: simple-debug
      condition: True
      action:
        debug:
          msg: "Простейшее событие срабатывает ({{ event | default('no event') }})"
