---
- name: Demo Rulebook
  hosts: localhost
  sources:
    - name: demo_source
      builtin:
        facts:
          demo_file_exists: true      # <-- хотя бы один факт, иначе будет пусто
  rules:
    - name: File created check
      condition: demo_file_exists == true
      actions:
        - debug:
            msg: "File /tmp/demo_file.txt detected — Rule fired!"
