---
- name: minimal-rulebook
  hosts: localhost

  # Источник событий — локальный, для теста
  sources:
    - ansible.eda.local: {}

  rules:
    - name: simple-debug
      condition: True
      action:
        debug:
          msg: "Событие сработало! Event: {{ event }}"
