---
- name: Demo Rulebook Kafka
  hosts: localhost
  sources:
    - name: kafka_source
      ansible.eda.kafka:
        bootstrap_servers: "kafka:9092"
        topics:
          - demo_topic
        group_id: "demo_group"
        auto_offset_reset: "earliest"
        session_timeout_ms: 10000      # 10 секунд
        heartbeat_interval_ms: 3000    # 3 секунды
  rules:
    - name: File created check
      condition:
        all:
          - fact:
              name: event.fileexists
              value: true
      actions:
        - action: debug
          action_args:
            msg: "File /tmp/demo_file.txt detected — Rule fired!"
