---
- name: Demo Rulebook
  hosts: localhost
  sources:
    - builtin: {}
  rules:
    - name: add_to_audit
      condition:
        AllCondition:
          - FactCondition:
              name: demo_task_done
              value: true
      actions:
        - Action:
            action: debug
            action_args:
              msg: "Demo task completed — adding to rule audit"
        - Action:
            action: set_fact
            action_args:
              fact_name: rule_audit
              fact_value: "{{ rule_audit | default([]) + ['Demo task executed at ' ~ ansible_date_time.iso8601] }}"
