---
- name: Demo Rulebook
  hosts: localhost
  sources:
    - name: demo_source
      source_name: builtin
      source_args: {}
  rules:
    - name: add_to_audit
      condition:
        all:
          - fact:
              name: demo_task_done
              value: true
      actions:
        - action: debug
          action_args:
            msg: "Demo task completed — adding to rule audit"
        - action: set_fact
          action_args:
            fact_name: rule_audit
            fact_value: "{{ rule_audit | default([]) + ['Demo task executed at ' ~ ansible_date_time.iso8601] }}"
